colors:
  grey:
    dark: 238
    light: 249
  red:
    dark: 1
    light: 196
  green:
    dark: 28
    light: 40
  yellow:
    dark: 3
    light: 11
  blue:
    dark: 32
    light: 38
  purple:
    dark: 5
    light: 13
  cyan:
    dark: 6
    light: 14
  white:
    dark: 7
    light: 15
  black: 
    dark: 16
    light: 8
  orange:
    dark: 202
    light: 208
styles:
  reset: 0
  bold: 1
  faint: 2
  italic: 3
  underline: 4
  blink-slow: 5
  blink-rapid: 6
  reverse-video: 7
  crossed-out: 9
  overlined: 53
color_reset: 15
